name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Run this workflow when pushing to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload artifact (all files)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
